SAMPLING_WEIGHTS:
  gemini-2.0-flash-exp: 3
  llama-3.2-90b-vision-instruct-maas: 3
  mistral-large-2411 : 3
  claude-3-5-sonnet@20240620 : 3
  gpt-4o-mini : 3
  
BATTLE_TARGETS:
  gemini-2.0-flash-exp: ["llama-3.2-90b-vision-instruct-maas", "mistral-large-2411", "claude-3-5-sonnet@20240620", "gpt-4o-mini"]
  llama-3.2-90b-vision-instruct-maas: ["gemini-2.0-flash-exp", "mistral-large-2411", "claude-3-5-sonnet@20240620", "gpt-4o-mini"]
  mistral-large-2411: ["gemini-2.0-flash-exp", "llama-3.2-90b-vision-instruct-maas", "claude-3-5-sonnet@20240620", "gpt-4o-mini"]
  claude-3-5-sonnet@20240620: ["gemini-2.0-flash-exp", "llama-3.2-90b-vision-instruct-maas", "mistral-large-2411", "gpt-4o-mini"]
  gpt-4o-mini: ["gemini-2.0-flash-exp", "llama-3.2-90b-vision-instruct-maas", "mistral-large-2411", "claude-3-5-sonnet@20240620"]

ANON_MODELS: []
SAMPLING_BOOST_MODELS:
  - gemini-2.0-flash-exp
  - llama-3.2-90b-vision-instruct-maas
  - mistral-large-2411
  - claude-3-5-sonnet@20240620
  - gpt-4o-mini
OUTAGE_MODELS: []