services:
  fastchat-controller:
    image: gptchat:latest
    container_name: fastchat-controller
    ports:
      - "21001:21001"
    env_file:
      - .env
    environment:
      - FASTCHAT_CMD=python3 -m fastchat.serve.controller --host 0.0.0.0 --port 21001
      
  fastchat-webui:
    image: gptchat:latest
    container_name: fastchat-webui
    depends_on:
      - fastchat-controller
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./application_default_credentials.json:/app/application_default_credentials.json
      - ./api_endpoint.json:/app/api_endpoint.json
    environment:
      - FASTCHAT_CMD=python3 -m fastchat.serve.gradio_web_server_cenia --controller-url http://fastchat-controller:21001 --register-api-endpoint-file /app/api_endpoint.json
  